name: Build APP (Mac)

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pythonセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: ライブラリインストール
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: APP作成
        run: |
          pyinstaller my_pyqt/study_abroad_replication.py \
            --add-data "my_pyqt/homepage_mock:homepage_mock" \
            --onefile

      - name: 成果物アップロード
        uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: dist/